### ISSUE TITLE
how it works

### ISSUE THREAD

**Issue by bumi** [bumi/kuvakehys#26]
opening this issue to discuss the wiki content: https://github.com/bumi/kuvakehys/wiki/How-does-it-work

@puneetbharill where would you see this text? because for example in step 3 you mention the newly created email address which we only have once the user has signed up. 
when we add the text to the form I think it is a bit too much. 

additionally I think we should explain the service - also how the service works. (like in addition to how signup works) 

shall I add the text to the homepage for now?

**Comment by puneetbharill** [comment]
I thought you wanted to make a hyperlink out of 'how it works' and put the text up there till we have some better images, flowchart or animation or whatever to replace the stuff that I wrote. 
Yes, the email address is a problem that's why I just called it 'album' as hopefully by the third step the person understands that the album name is associated with the email address but I agree with you, I am not very satisfied with that either. I can change that, or please change it if you think of better wording and we can discuss further. 
Could you elaborate a bit on how the service works parts. What would you like me to emphasise on. You mean the costs? print sizes etc etc?

**Comment by bumi** [comment]
ok, let me just put the text directly on the homepage. (not hidden behind a link)

with the "service parts" I mean that currently we do not explain what the service is actually used for. (we explain how to signup in your 3 steps, and inderectly that you get some photos when you send them to that email) But we never say what it is actually good for and why to use it.

**Comment by puneetbharill** [comment]
Got it, I will work on the service part and put something up soon.

**Comment by bumi** [comment]
:dancers:
